services:
    traefik:
        image: 'traefik:latest'
        ports:
            - '80:80'
            - '443:443'
            - '5432:5432'
        restart: always
        networks:
            - traefik
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik.yml:/etc/traefik/traefik.yml:ro
            - ./static/log:/var/log/traefik
            - ./static/letsencrypt:/letsencrypt
            - ./dynamic:/etc/traefik/dynamic:ro
            - ./static/ca/rootCA.pem:/etc/ssl/cacert.pem:ro
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.traefik.rule=Host(`traefik.test`)'
            - 'traefik.http.routers.traefik.service=api@internal'
            - 'traefik.http.services.traefik.loadbalancer.server.port=8080'
            - 'traefik.http.routers.traefik.entrypoints=http,https'
            - 'traefik.http.routers.traefik.tls=true'
            - 'prvious.ssl.enable=true'
            - 'prvious.ssl.domains=traefik.test,*.traefik.test'

    ssl:
        image: 'ghcr.io/prvious/ssl:latest'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - './static/letsencrypt:/app/files/certs'
            - './static/ca:/app/files/ca'
            - './dynamic/conf/tls.yml:/app/files/traefik/tls.yml'
        networks:
            - traefik
        environment:
            - CHECK_INTERVAL=10000
            - CERT_DIR=/letsencrypt/
        restart: always

networks:
    traefik:
        external: true
    haproxy:
        external: true
