entryPoints:
    http:
        address: ":80"
        # http:
        #     redirections:
        #         entryPoint:
        #             to: https
        #             scheme: https
    https:
        address: ":443"

    # Add a dedicated TCP entryPoint for Postgres SNI routing
    pg:
        address: ":5432"

providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        network: "traefik"
        exposedByDefault: false
    file:
        directory: "/etc/traefik/dynamic/conf/"
        watch: true

api:
    dashboard: true

log:
    level: INFO
